# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0007_statuscheckresult_consecutive_failures'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='http_body',
            field=models.TextField(blank=True, default=None, help_text=b'HTTP body.', null=True),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='http_body_type',
            field=models.CharField(choices=[(b'Raw', b'Raw'), (b'JSON', b'JSON'), (b'YAML', b'YAML')], default=b'Raw', help_text=b'The body type.', max_length=10),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='http_method',
            field=models.CharField(choices=[(b'GET', b'GET'), (b'POST', b'POST'), (b'HEAD', b'HEAD')], default=b'GET', help_text=b'The method to use for invocation.', max_length=10),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='http_params',
            field=models.TextField(blank=True, default=None, help_text=b'Yaml representation of "header: value" to send as parameters.', null=True),
        ),
    ]
