# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-02 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabotapp', '0008_auto_20180502_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='http_headers',
            field=models.TextField(blank=True, default=None, help_text=b'Yaml representation of "header: value" to send as headers.', null=True),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='http_params',
            field=models.TextField(blank=True, default=None, help_text=b'Yaml representation of "key: value" to send as parameters.', null=True),
        ),
    ]
